[build]
  publish = "src"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/reservation-classique"
  to = "/reservation-classique.html"
  status = 200

[[redirects]]
  from = "/reservation-anniversaire"
  to = "/reservation-anniversaire.html"
  status = 200

[[redirects]]
  from = "/battle-royale"
  to = "/battle-royale.html"
  status = 200

[[redirects]]
  from = "/tableau"
  to = "/tableau.html"
  status = 200
